ALTER TABLE "Topic" ADD COLUMN "order" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Post" ADD COLUMN "order" DOUBLE PRECISION NOT NULL DEFAULT 0;

UPDATE "Topic" SET "order" = EXTRACT(EPOCH FROM "createdAt");
UPDATE "Post" SET "order" = EXTRACT(EPOCH FROM "createdAt");
